spring:
  kafka:
    consumer:
      group-id: order-ingestion-fmsorderhandler-stage
      cancel-order-group-id: order-ingestion-fmscancellation-handler-stage
    dlq-consumer:
      group-id: order-ingestion-dlq-fms-order-handler-stage
    producer:
      fms-producer-topic: FULFILLMENT_STATUS_UPDATES_NONPROD_THOR
      customer-cancellation-topic: endgame-oi-pt-cancellation-stg

customer-po-topic: customer-purchase-orders-stg