management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

  metrics:
    enable:
      jvm: true

    export:
      prometheus:
        histogram-flavor: prometheus

  endpoint:
    health:
      group:
        liveness:
          include: "*"
        readiness:
          include: "*"
      probes:
        enabled: true
azure:
  cosmos:
    uri: ${COSMOS_ENDPOINT}
    key: ${COSMOS_KEY}
    database: ${EPHEMERAL_ENV_ID}

spring:
  jmx:
    enabled: true
  config:
    import: optional:configtree:./secrets/,optional:configtree:/etc/secrets/
  kafka:
    bootstrap-servers: ${ENDGAME_BROKERS}
    consumer:
      group-id: order-ingestion-fms-listener-pr
      fms-consumer-topic: FULFILLMENT_ORDER_OUTBOUND_NONPROD-pr
    producer:
      fms-producer-topic: FULFILLMENT_STATUS_UPDATES_NONPROD_THOR-pr
      packman-input-topic: thor-packman-input-pr
      endgame-producer-topic: customer-purchase-orders-pr

listener-config:
  ship-node-to-fcid:
    9615: 9610
    7439: 7441
    28021: 7552
    29821: 3006
    31341: 3124